### ISSUE TITLE
Document when to use reactivestreams::Subscriber vs SubscriberBase

### ISSUE THREAD

**Issue by lexs** [ReactiveSocket/reactivesocket-cpp#174]
We have both `SubscriberBase` and the reactivestreams `Subscriber` but it might not be clear how they are different, this should be documented.

**Comment by lehecka** [comment]
I disagree with this. The base interface should always be available because there could be different implementations of the "convenience" base classes. SubscriberBase also brings some overhead (Executors, SubdscriptionShim, etc.) which might not be necessary in some cases.
I agree to encourage the use of SubscriberBase and discourage the use of Subscriber.

**Comment by lexs** [comment]
@lehecka That works for me, I'll rename this task.

**Comment by yschimke** [comment]
documented:


//
// SubscriberBase is designed to be a general purpose base class for
// implementors of Subscriber<T> interface. It provides 2 key features:
// 1. ExecutorBase: You can specify the Executor you want to use to execute the
//    on{Subscribe,Next,Complete,Error} methods. Eq. by providing EventBase
//    as an executor, you can call the methods from any thread and the
//    marshaling to the right EventBase thread will happen automatically.
// 2. once the user cancels the subscriber via the subscription::cancel, it is
//    guaranteed that no more callbacks will be called. It is safe for the
// client to do cleanup and releasing of resources. User doesn't have to call
//    subscription::cancel in on{Complete,Error} methods.
//
