### ISSUE TITLE
StandardReactiveSocket::StandardReactiveSocket forces creation on RS eventbase

### ISSUE THREAD

**Issue by martinsix** [ReactiveSocket/reactivesocket-cpp#275]
the constructor has a call to debugCheckCorrectExecutor() currently. Why? I understand that we can only connect on the right eventbase, but why do we have to create the socket in a disconnected state on that eventbase too?

**Comment by lehecka** [comment]
The reason why is that StandardReactiveSocket and its state machines are not implemented with any multithreading synchronization. So if we would allow RS to be creates by any thread, the eventBase thread would read invalid memory values due to instruction reordering.
We will eventually move away from this model, but currently for correctness we require RS instances to be created and be called by the executor thread only.

**Comment by martinsix** [comment]
Does this apply to disconnected sockets as well? There should be nothing calling into ReactiveSocket until we connect, right?
