### ISSUE TITLE
ConnectionAutomaton should ignore messages for streams it closed

### ISSUE THREAD

**Issue by lehecka** [ReactiveSocket/reactivesocket-cpp#53]
I found this bug:
The server sends 2 payloads on a RS subscription. The client receives the first payload and cancels the subscription. Under the covers the client ConnectionAutomaton closes the RS stream. Then the second payload comes for the subscription. The ConnectoinAutomaton is now failing to find the stream and tries to handle the unknown stream and fails.

The core issues seems to be that there could be payloads to process between cancel and onComplete.

The fix should be either:
1. the ConnectionAutomaton ignores payloads for a closed stream, or
2. the underlying duplex connection will never try to deliver another payload after the the input subscription is canceled. I think this fix would not work in multithreaded environment, thou.

**Comment by yschimke** [comment]
I can a look tomorrow starting with the approach 1 and the logic we discussed on the board.

**Comment by stupaq-fb** [comment]
Both 1. and 2. have the same problem: in principle, you don't know what you don't know.

After a stream is closed, we have to remove _all_ information about it from internal data structures, otherwise we would leak memory. Hence, when we see the same stream ID again, we don't know if it's an old one or a new one. Current implementation assumes the former.

The only rock-solid solution is to fix TODO(s) in ConnectionAutomaton, namely https://github.com/ReactiveSocket/reactivesocket-cpp/blob/master/reactivesocket-cpp/src/ConnectionAutomaton.cpp#L195. We may require stream IDs to be monotonically increasing, I believe. This way you don't need to remember all stream IDs used by the remote end, but only the last one.

There are many corner cases around connection-level events, because connection automaton is simply not implemented :), see #7. Would be good if someone picked that one up, otherwise we can create 100s of issues like this one.

**Comment by yschimke** [comment]
Option 1 is viable at least for ourselves, the spec says

> Once a stream has "terminated", the Stream ID can be "forgotten" by the Requester and Responder. An implementation MAY re-use an ID at this time, but it is recommended that an implementation not aggressively re-use IDs.

So we have the option for streams created by our side of knowing whether its active or not, and assuming unknown ids higher than our max generated id are an error, and less than are a timing error.  

When they wrap we can no longer definitively say its an error, but I suspect we don't handle this cleanly, e.g. do we check new ids are not already active? I'd ignore this for now.

I don't actually see why the protocol spec differs from HTTP/2 which disallows reuse

https://tools.ietf.org/html/rfc7540#page-21

**Comment by stupaq-fb** [comment]
Under the assumption that we store amount of data linear in the number of active streams only and do not have unsubscribe handshake over the network, I don't think it's possible to allow for stream reuse without running into the problems like this one.

Ultimately, DuplexConnection passes frames asynchronously, so if one party, say subscriber requester, terminates the stream, it might receive a frame sent by the remote end before the termination reached it and after arbitrarily long time after the termination was issued by requester.

BTW, this is a similar issue as with ReactiveStreams semantics, where I simply enforce unsubscribe handshake to happen. We shouldn't do it over the network, so my vote is to disallow ID reuse.

**Comment by yschimke** [comment]
If we conclude this, I suggest we put a PR out to strengthen the spec wording

**Comment by yschimke** [comment]
I put up two alternatives for discussion in the PR I raised, comments or concerns from both of you would be good.  https://github.com/ReactiveSocket/reactivesocket/pull/92

**Comment by stupaq-fb** [comment]
Okay, based on my understanding of the discussion, we need to alter the spec to fix it.

In a meantime, if it's causing troubles for your testing, I can hack up a temporary fix. @lehecka, how much of an annoyance it is for your testing?

**Comment by yschimke** [comment]
I'm got some local changes based on where it seems the spec is heading.  If it's urgent then @stupaq-fb should obviously do it, but if not I'd like to continue with it to get up to speed.

**Comment by stupaq-fb** [comment]
Absolutely, I'm happy not to do it :D feel free to publish a WIP, if some parts of the ConnectionAutomaton are not clear we can discuss them on the diff.

**Comment by lehecka** [comment]
done. frames for closed streams are ignored
