### ISSUE TITLE
Remove hard dependency on folly

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-cpp#61]
Talking wth @benjchristensen, and second hand from @tmontgomery

We would ideally avoid having a hard dependency on folly.  We should be able to build and run reactivesocket-cpp tests without folly.  But then bind against folly for fb specific code.

Our TCP implementation might use folly AsyncSocket, but other implementations should be possible without building folly.

Q: Is there an open source alternative for our tests?
Q: What would Payload look like (since it is part of the ReactiveSocket public API), if an app wanted to use two transports one of which used folly:IOBuf e.g. proxygen and another used an open source alternative e.g. Aeron?

**Comment by yschimke** [comment]
cc @stupaq-fb @lehecka

**Comment by stupaq-fb** [comment]
Generally agree, but there are two questions here:
1. How do we get rid of folly from public headers?
2. How do we get rid of folly from the implementation?

I'd focus on 1. first.

> Is there an open source alternative for our tests?

What is "not open source" about our tests?

**Comment by yschimke** [comment]
Bad choice of words.  Should our tests still run with folly (which is obviously open source), or is there some ubiquitous buffer type we would use instead.  or byte[]?

**Comment by stupaq-fb** [comment]
Both. We may decide to run tests with folly::IOBuf-based Payload only internally. Depends on how complicated the interface of that buffer type ends up being. 

Sounds like you want to turn Payload into an interface of some sort. Is that right?

**Comment by yschimke** [comment]
I don't think I'm best placed to make that call.  I suspect that if you know you are using ReactiveSocket + Proxygen you just want the payload to be an IOBuf and not wrapped in an interface where you may have to copy.

**Comment by stupaq-fb** [comment]
The interface may be comprehensive enough to express all of the functionality of IOBuf. It would be rather ugly, but not fundamentally impossible. We could also reimplement a subset of IOBuf and provide methods to unsafely (but efficiently) convert one into another. I think IOBuf allows one to take an ownership over an arbitrary char* and specify offsets.

**Comment by benjchristensen** [comment]
@tmontgomery needs to weigh in on this. He told me has an approach to solving this involving templates.

**Comment by stupaq-fb** [comment]
We can parametrise entire ReactiveSocket on payload type, but hope that wasn't part of the solution :D

**Comment by tmontgomery** [comment]
This has been my initial thinking. Things will evolve. I've been looking at CMake build first.

I was thinking we could parameterize DuplexConnection and then use it as the means to handle all IOBuf style requests and handling. Same method signatures and use CTRP-style binding. With an IOBuf-like API. Transport and memory management are normally closely tied, so having the buffer management be a parameter of DuplexConnection would seem to "feel" like the right thing from a high level.

If we figure out that DuplexConnection isn't the right thing to parameterize, we can make it another interface that is passed in. For cleanliness, I would not parameterize the ReactiveSocket. The IOBuf style management is a config option, just like the transport is. So, would rather pass in the config rather than parameterize it.

We should also trim down IOBuf and use a subset of what it does as much as possible.

For the build, the CMake build should have an option to use folly or not. When set to use folly, then it can use things as normal (and have a thin shim to convert from the IOBuf-like API into a pimpl that is just IOBuf and will be passed through by the optimizer as much as possible). When not set to use folly, RS-cpp can just use its own minimal IOBuf-like management.

**Comment by lehecka** [comment]
@tmontgomery : when you say parametrize DuplexConnection, do you mean C++ template parameter or a passing down an instance of the iobuf factory?

**Comment by tmontgomery** [comment]
Template param was my initial thought to avoid sprawl, but I am not totally wedded to it. Essentially, I think it is good to have it come in via something like DuplexConnection and decouple the usage of IOBuf from the implementation of IOBuf.

**Comment by tmontgomery** [comment]
An advantage, IMO, is that a template param of DuplexConnection makes it a compile time decision.

**Comment by stupaq-fb** [comment]
@tmontgomery I like the idea of tying this decision to DuplexConnection, not sure about static/dynamic binding.

If we make the Payload type a template param of DuplexConnection, then we have to make it a template param of ReactiveSocket (or make DuplexConnection a template param of ReactiveSocket, or something like that), right? How would a signature of ReactiveSocket::requestResponse look like otherwise? So this approach is equivalent to parametrising (almost) everything on Payload type and putting large portion of the library in headers, and that doesn't sound amazing to me.

**Comment by tmontgomery** [comment]
@stupaq-fb One way to do this, and yes, it is rather ugly, is to conditionally make the type based on the presence (or absence) of folly. Either using `using` or an actual typedef to clean up the signature. In that case, we are only making it cleaner and allowing the type system to do all the work. That does cause sprawl of the param normally. I'm OK with header heavy libs, actually. As long as the dependencies are 0, that is.

The only real reason to make the decision of "which IOBuf impl" to use a param is to avoid vtable overhead. If it looks too ugly and is too restrictive, it might be cleaner to just take the overhead. The less IOBuf surface area used, the less likely that overhead is to be non-trivial.

In reality, the decision made at compile time is to use folly or the local IOBuf implementation for all ReactiveSockets. We might not need to make it a param. It may just be a class (or namespace) that has 2 impls. And only one that is conditionally compiled in. Not a common interface (or methods), just conditionally compile one impl vs. another.

BTW, by "impl" above, I am thinking of the general term. PIMPL has its place, though.

**Comment by yschimke** [comment]
Would something like a reactivesocket proxy between proxygen and aeron duplex connections, still be possible?  Somehow the generics would somehow figure out that an additional copy from IOBuf to Aeron bufs might be necessary over some optimised 0-copy aeron to aeron case?

**Comment by tmontgomery** [comment]
Aeron should be simple to add if the internal `void *` or similar is accessible.

**Comment by stupaq-fb** [comment]
So it seems that one class of approaches involves parametrising pretty much everything on Payload type, including DuplexConnection and ReactiveSocket object. That one allows us to instantiate ReactiveSocket for different Payloads in the same binary, but the code looks a bit ugly, as Payload type needs to be wired all the way through every component that operates on any buffer. So we have `template<typename Payload> class ReactiveSocket {...};`, `template<typename Payload> class DuplexConnection {...};`, etc...

Second class: dynamic dispatch.

Third class: conditional compilation. We can only use one type of Payload in a binary. We'd have to prevent people from loading .so ReactiveSocket into a binary that's been compiled with different buffer type...

Fourth class: reimplement a subset of IOBuf and provide fast conversions between IOBuf and this type for the "common cases". That doesn't sound terrible to me.

**Comment by lehecka** [comment]
I agree with @stupaq-fb . My excitement on template parametrizing everything on Payload is close to 0. It doesn't feel like a practical solution to me.

I am most in favor of whats described as the fourth class of solution in the post above.
My approach would be:
1. see how difficult is it to break folly into a smaller libs
2. see if we can extend follys cmake file to build only a small lib with IOBuf
3. if the 2 points above are dead ends, then fork IOBuf from folly.
4. if all 3 points above fail, then use some other dynamic buffer structure.

**Comment by tmontgomery** [comment]
@stupaq-fb The more we discuss, the more I like the fourth.

The first does have some sprawl, but it could be managed a bit better. And at the end of the day, it may not be worth it. It's a bit overkill anyway.

The third would require some of the stuff from the fourth anyway, I think.

**Comment by yschimke** [comment]
I think this ship has sailed, closing
